### ISSUE TITLE
Cannot find module '././dist/ririkoCli'

### ISSUE THREAD

**Issue by TunxxVN** [RirikoAI/RirikoBot#322]
![Screenshot_2024_0211_211520](https://github.com/RirikoAI/RirikoBot/assets/142597374/03b74ca3-d8ed-44a6-bfcd-40db31559081)

I got this error when starting bot, I have filled everything in .env

Nodejs version: 18.19.0
```[tasklist]
### Tasks
```

**Comment by earnestangel** [comment]
Hi, can you try these @TunxxVN 

1. remove the dist folder
2. reinstall dependencies by deleting the node_modules folder and running: npm i --include=dev 
3. rerun: npm run start

**Comment by earnestangel** [comment]
Closing this issue due to no reply.
