### ISSUE TITLE
what is the provider do i put

### ISSUE THREAD

**Issue by COMPLEX2323** [RirikoAI/RirikoBot#67]
what do i put there

**Comment by earnestangel** [comment]
Need more information, what kind of provider? Do you mean the AI service provider?

**Comment by COMPLEX2323** [comment]
i fixed it i looked at the code

**Comment by COMPLEX2323** [comment]
nice bot is there other things coming to it

**Comment by earnestangel** [comment]
Thanks ^^ I started the whole thing like 2 days ago. Huge developments coming soon. I'm planning to add these features:
Welcomer, some basic Moderation Tools, free games announcer (EpicGames), Giveaway, live stream announcer, reaction roles, some basic fun commands and ticketing.

Anime commands are pretty much done. Will start documenting when developments for the features are done.

**Comment by COMPLEX2323** [comment]
you should add a dashborad

**Comment by earnestangel** [comment]
Now you can set the AI from the config file or the .env file. Must be one of: NLPCloudProvider or OpenAIProvider
